"""
Django settings for loganalyzer project.

Generated by 'django-admin startproject' using Django 3.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

from django.core.exceptions import ImproperlyConfigured


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    normalized = value.strip().lower()
    if normalized in ('1', 'true', 'yes', 'on'):
        return True
    if normalized in ('0', 'false', 'no', 'off'):
        return False
    raise ImproperlyConfigured(
        "%s must be one of true/false, 1/0, yes/no, or on/off" % name
    )


def env_list(name, default=''):
    return [
        item.strip() for item in os.environ.get(name, default).split(',')
        if item.strip()
    ]


def env_value(name, default=''):
    value = os.environ.get(name)
    return value if value not in (None, '') else default

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_value(
    'DJANGO_SECRET_KEY', 'local-development-only-change-me'
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

if not DEBUG and SECRET_KEY == 'local-development-only-change-me':
    raise ImproperlyConfigured(
        'DJANGO_SECRET_KEY must be set when DJANGO_DEBUG is false'
    )

# To use local ip not localhost, 127.0.0.1
# npm run serve 172.16.1.110:8000
# Need to change in production
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,backend'
)

MEDIA_URL = '/media/'
#MEDIA_URL = 'E:\loganalyzerMedia'
#MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = env_value(
    'DJANGO_MEDIA_ROOT', os.path.join(BASE_DIR, 'media')
)
# MEDIA_ROOT = 'C:\loganalyzerMedia'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'loganalyzerapi',
    'corsheaders',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'dynamic_models',
]

DYNAMIC_MODELS = {
    'USE_APP_LABEL': 'loganalyzerapi'
}


SITE_ID = 1
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'none'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],    
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
# 로그인하지 않으면 API 호출 시 401 리턴(테스트 위해 주석처리)	
#    'DEFAULT_PERMISSION_CLASSES': (
#        'rest_framework.permissions.IsAuthenticated',
#    ),
}

ROOT_URLCONF = 'loganalyzer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'loganalyzer.wsgi.application'

CORS_ORIGIN_ALLOW_ALL = env_bool('DJANGO_CORS_ALLOW_ALL', DEBUG)

CORS_ORIGIN_WHITELIST = env_list(
    'DJANGO_CORS_ORIGINS',
    'http://localhost:8080,http://127.0.0.1:8080',
)

if not DEBUG and CORS_ORIGIN_ALLOW_ALL:
    raise ImproperlyConfigured(
        'DJANGO_CORS_ALLOW_ALL must be false when DJANGO_DEBUG is false'
    )


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''
DATABASES = {
	'default': {
	'ENGINE': 'django.db.backends.postgresql' ,
    'NAME': env_value('POSTGRES_DB', 'mwla2'),
    'USER': env_value('POSTGRES_USER', 'postgres'),
	'PASSWORD': env_value('POSTGRES_PASSWORD', 'postgres'),
    'HOST': env_value('POSTGRES_HOST', 'localhost'),
	'PORT': env_value('POSTGRES_PORT', '5432'),
	}
}

# The Vue client uses DRF token authentication. Keep registration and login
# responses compatible with the existing {"key": "..."} API contract.
REST_AUTH = {
    'REGISTER_SERIALIZER': 'loganalyzerapi.registration.RegistrationSerializer',
    'SESSION_LOGIN': False,
    'USE_JWT': False,
}

LOG_PARSER_SPLIT_SIZE_BYTES = int(env_value(
    'LOG_PARSER_SPLIT_SIZE_BYTES', str(int(1.5 * 1024 * 1024 * 1024))
))
LOG_PARSER_MAX_EXPANDED_BYTES = int(env_value(
    'LOG_PARSER_MAX_EXPANDED_BYTES', str(10 * 1024 * 1024 * 1024)
))
# Original project-specific tables are the operational default. V2 mirroring
# is opt-in for migration validation, never an implicit upload cost.
LOG_STORAGE_MODE = env_value('LOG_STORAGE_MODE', 'dynamic').lower()
if LOG_STORAGE_MODE not in {'dynamic', 'dual', 'v2'}:
    raise ValueError('LOG_STORAGE_MODE must be dynamic, dual, or v2')


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Preserve the primary-key type used by the existing schema and migrations.
# Django 3.2 otherwise defaults new models to BigAutoField.
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

# Logging
LOG_TO_FILE = env_bool('DJANGO_LOG_TO_FILE', True)
LOG_DIRECTORY = env_value(
    'DJANGO_LOG_DIR', os.path.join(BASE_DIR, 'logs')
)
if LOG_TO_FILE:
    os.makedirs(LOG_DIRECTORY, exist_ok=True)

LOG_HANDLERS = ['console']
if LOG_TO_FILE:
    LOG_HANDLERS.append('file')

LOG_HANDLER_CONFIG = {
    'console': {
        'level': 'INFO',
        'filters': ['require_debug_true'],
        'class': 'logging.StreamHandler',
        'formatter': 'verbose'
    },
}
if LOG_TO_FILE:
    LOG_HANDLER_CONFIG['file'] = {
        'level': 'INFO',
        'class': 'logging.handlers.TimedRotatingFileHandler',
        'filename': os.path.join(LOG_DIRECTORY, 'mwla.log'),
        'formatter': 'verbose',
        'when': 'midnight',
        'backupCount': 30,
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format' : "[%(levelname)s][%(asctime)s,%(msecs)3d][%(process)d|%(thread)d][%(name)s|%(funcName)s|%(lineno)s] %(message)s",
            'datefmt' : "%d/%b/%Y %H:%M:%S"
        },
    },
    'filters': {
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': LOG_HANDLER_CONFIG,
    'loggers': {
        'loganalyzerapi': {
            'handlers': LOG_HANDLERS,
            'level': 'INFO',
            'propagate': True,
        },
    }
}
