# Generated by Django 3.0.4 on 2026-08-11 07:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('metric_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='mid')),
                ('metric_kind', models.CharField(max_length=10)),
                ('metric_type', models.CharField(default='Info', max_length=10)),
                ('metric_definition', models.CharField(max_length=500)),
                ('metric_filter', models.CharField(max_length=500)),
                ('metric_filter2', models.CharField(default='0', max_length=10)),
                ('metric_unit', models.CharField(max_length=10)),
                ('metric_value1', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_value2', models.CharField(blank=True, max_length=100, null=True)),
                ('metric_static', models.CharField(max_length=1)),
                ('creator', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='logfile',
            name='instance_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logfile',
            name='server_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='freserve1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='freserve2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='freserve3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='ftime_taken',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='file_format',
            field=models.CharField(max_length=400),
        ),
        migrations.CreateModel(
            name='LogMasterMetric',
            fields=[
                ('logmastermetric_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='lmid')),
                ('creator', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loganalyzerapi.Metrics')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loganalyzerapi.LogMaster')),
            ],
            options={
                'ordering': ['created'],
                'unique_together': {('project', 'metric')},
            },
        ),
    ]
