# Generated by Django 3.0.4 on 2020-09-09 10:44

from django.db import migrations, models
import django.db.models.deletion
import loganalyzerapi.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogFormat',
            fields=[
                ('format_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='fid')),
                ('format_kind', models.CharField(max_length=50)),
                ('format_name', models.CharField(max_length=50)),
                ('format_strings', models.CharField(max_length=500)),
                ('creator', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='LogFormatString',
            fields=[
                ('formatstring_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='fsid')),
                ('format_kind', models.CharField(max_length=50)),
                ('format_string', models.CharField(max_length=50)),
                ('format_definition', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='LogMaster',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='pid')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=300)),
                ('creator', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('logfile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='fid')),
                ('file_name', models.CharField(blank=True, default='', max_length=100)),
                ('file_object', models.FileField(upload_to=loganalyzerapi.models.upload_directory_path)),
                ('file_format', models.CharField(max_length=200)),
                ('format_kind', models.CharField(max_length=50, null=True)),
                ('format_name', models.CharField(max_length=50, null=True)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loganalyzerapi.LogMaster')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('logdetail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='did')),
                ('log_line', models.CharField(blank=True, max_length=1000, null=True)),
                ('fyear', models.CharField(blank=True, max_length=4, null=True)),
                ('fmonth', models.CharField(blank=True, max_length=2, null=True)),
                ('fday', models.CharField(blank=True, max_length=2, null=True)),
                ('fhour', models.CharField(blank=True, max_length=2, null=True)),
                ('fminute', models.CharField(blank=True, max_length=2, null=True)),
                ('fsecond', models.CharField(blank=True, max_length=2, null=True)),
                ('fdate', models.CharField(blank=True, max_length=8, null=True)),
                ('ftime', models.CharField(blank=True, max_length=6, null=True)),
                ('fdatetime', models.CharField(blank=True, max_length=14, null=True)),
                ('frequest', models.CharField(blank=True, max_length=500, null=True)),
                ('fip', models.CharField(blank=True, max_length=40, null=True)),
                ('freferer', models.CharField(blank=True, max_length=500, null=True)),
                ('fuser_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('fstatus', models.CharField(blank=True, max_length=10, null=True)),
                ('ftime_taken', models.IntegerField(default=0)),
                ('fbyte', models.IntegerField(default=0)),
                ('fextension', models.CharField(blank=True, max_length=10, null=True)),
                ('freserve1', models.CharField(blank=True, max_length=200, null=True)),
                ('freserve2', models.CharField(blank=True, max_length=200, null=True)),
                ('freserve3', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
                ('logfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loganalyzerapi.LogFile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
