# Generated by Django 3.0.4 on 2020-06-15 06:42

from django.db import migrations, models
import django.db.models.deletion
import loganalyzerapi.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogMaster',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='pid')),
                ('project_name', models.CharField(max_length=50)),
                ('project_description', models.TextField(max_length=300)),
                ('file_format', models.CharField(max_length=100)),
                ('uploader', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='LogFile',
            fields=[
                ('logfile_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='fid')),
                ('file_name', models.CharField(blank=True, default='', max_length=100)),
                ('file_path', models.FileField(upload_to=loganalyzerapi.models.upload_directory_path)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loganalyzerapi.LogMaster')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='LogDetail',
            fields=[
                ('logdetail_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='did')),
                ('log_line', models.CharField(blank=True, max_length=300, null=True)),
                ('fyear', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('fmonth', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('fday', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('fhour', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('fminute', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('fsecond', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('frequest', models.CharField(blank=True, max_length=300, null=True)),
                ('fip', models.CharField(blank=True, max_length=40, null=True)),
                ('freferrer', models.CharField(blank=True, max_length=200, null=True)),
                ('fuser_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('fstatus', models.CharField(blank=True, max_length=10, null=True)),
                ('ftime_taken', models.SmallIntegerField(default=0)),
                ('freserve1', models.CharField(blank=True, max_length=200, null=True)),
                ('freserve2', models.CharField(blank=True, max_length=200, null=True)),
                ('freserve3', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
                ('logfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loganalyzerapi.LogFile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
