# Generated by Django 3.0.4 on 2020-06-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logdetail',
            name='freferrer',
        ),
        migrations.AddField(
            model_name='logdetail',
            name='fdate',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='logdetail',
            name='freferer',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='logdetail',
            name='ftime',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='fday',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='fhour',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='fminute',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='fmonth',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='frequest',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='fsecond',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='fuser_agent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='fyear',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='logdetail',
            name='log_line',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
