# Generated by Django 3.0.4 on 2020-06-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0002_auto_20200619_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdetail',
            name='fdatetime',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
