# Generated by Django 3.0.4 on 2020-06-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0003_logdetail_fdatetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logfile',
            old_name='file_path',
            new_name='file_object',
        ),
        migrations.RemoveField(
            model_name='logmaster',
            name='file_format',
        ),
    ]
