# Generated by Django 3.0.4 on 2020-06-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0004_auto_20200629_1941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logmaster',
            old_name='uploader',
            new_name='creator',
        ),
    ]
