# Generated by Django 3.0.4 on 2020-06-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0005_auto_20200630_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='file_format',
            field=models.CharField(default='%h %l %u %t "%r" %>s %b', max_length=100),
            preserve_default=False,
        ),
    ]
