# Generated by Django 3.0.4 on 2020-07-02 01:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0006_logfile_file_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogFormat',
            fields=[
                ('format_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='fid')),
                ('format_kind', models.CharField(max_length=50)),
                ('format_name', models.CharField(max_length=50)),
                ('format_strings', models.CharField(max_length=500)),
                ('creator', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='LogFormatString',
            fields=[
                ('formatstring_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='fsid')),
                ('format_kind', models.CharField(max_length=50)),
                ('format_string', models.CharField(max_length=50)),
                ('format_definition', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now=True, verbose_name='date create')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
