# Generated by Django 3.0.4 on 2020-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0007_logformat_logformatstring'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='format_kind',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='logfile',
            name='format_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
