# Generated by Django 3.0.4 on 2020-07-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0008_auto_20200715_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='file_format',
            field=models.CharField(max_length=200),
        ),
    ]
