# Generated by Django 3.0.4 on 2020-07-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loganalyzerapi', '0009_auto_20200717_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdetail',
            name='ftime_taken',
            field=models.IntegerField(default=0),
        ),
    ]
