# 프로젝트 키(고유값)
sonar.projectKey=com.sds.project:uidev:reactnative_firebase
# 프로젝트 이름 - 소나큐브UI에 보여지는 이름
sonar.projectName=PJT:uidev:vuejs_opus_sample
# 프로젝트 버전
sonar.projectVersion=0.0.1

# 소스코드 경로
# 설정하지 않을 경우 분석 시작위치는 sonar-project.properties 파일의 위치
sonar.sources=./src

# 소스코드 인코딩 정보
sonar.sourceEncoding=UTF-8

# (옵션) 분석 언어 설정 - 설정하지 않을 경우 모든 언어 분석
# sonar.language=js

# 소나큐브 서버 정보
sonar.host.url=http://70.121.224.128:9991
sonar.login=analyzer
sonar.password=analyzer

# (옵션) 분석 범위 설정 - 와일드카드(*/**/?) 사용 가능
